CREATE TABLE IF NOT EXISTS payment (
  id INT AUTO_INCREMENT PRIMARY KEY,
  reservation_id INT NOT NULL,
  status ENUM('REQUESTED','AUTHORIZED','FAILED') NOT NULL,
  amount DECIMAL(10,2),
  currency CHAR(3)
);