FROM node:20-alpine AS build

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# serve via a simple web server (nginx)
FROM nginx:1.25-alpine
COPY --from=build /usr/src/app/dist /usr/share/nginx/html

EXPOSE 5173
CMD ["nginx", "-g", "daemon off;"]
