CREATE TABLE payment (
  id INT AUTO_INCREMENT PRIMARY KEY,
  reservation_id INT NOT NULL,
  status ENUM('REQUESTED','AUTHORIZED','FAILED') NOT NULL,
  amount DECIMAL(10,2),
  currency CHAR(3)
);

CREATE TABLE outbox (
  id INT AUTO_INCREMENT PRIMARY KEY,
  type VARCHAR(50),
  payload JSON,
  published BOOLEAN DEFAULT 0
);
