apiVersion: apps/v1
kind: Deployment
metadata: { name: notification }
spec:
  replicas: 1
  selector: { matchLabels: { app: notification } }
  template:
    metadata: { labels: { app: notification } }
    spec:
      containers:
      - name: notification
        image: yourrepo/notification:latest
        ports: [{ containerPort: 3000 }]
        env:
        - { name: KAFKA_BROKERS, value: "kafka:9092" }
        - { name: SCHEMA_REGISTRY_URL, value: "http://kafka:8081" }
---
apiVersion: v1
kind: Service
metadata: { name: notification }
spec:
  selector: { app: notification }
  ports:
  - port: 3000
    targetPort: 3000
